### ISSUE TITLE
Migrating to the new JHipster website

### ISSUE THREAD

**Issue by jdubois** [jhipster/jp#36]
Hello! We've been working on doing a new re-design of the main JHipster website, and we would love to include you!

The discussion is at https://github.com/jhipster/jhipster.github.io/pull/1357

Would like to continue working on the translation? And the old design should continue to work, but it would be better to migrate, are you interested in this?

For your information, I'm doing a similar message to the Chinese translation team.

**Comment by hide212131** [comment]
@jdubois I'm sorry! I missed the issue and this pull request: https://github.com/jhipster/jhipster.github.io/pull/1357. (I was excitedly following along here though... https://groups.google.com/g/jhipster-dev/c/BHXtFSZJ9Fg/m/3RCiovPzAgAJ 😢) I will get started on the new site changes as soon as possible. Please bear with me.

**Comment by jdubois** [comment]
Oh no problem, we have time! The new design is much cleaner, but it is the same content in the end, so I hope it won't be difficult for you.

**Comment by hide212131** [comment]
@jdubois Sorry for the delay, but the new site has been updated!
https://www.jhipster.tech/jp/

Currently, it’s based on version v8.7.0, but I’ll update it soon! 
I’d also like to discuss the language switcher with you later.

**Comment by hide212131** [comment]
@jdubois
- I have updated the Japanese site to the latest version!
- A language switcher has been implemented on the Japanese site.
- [A pull request](https://github.com/jhipster/jhipster.github.io/pull/1416) has been submitted to add the language switcher to the English site.
